### ISSUE TITLE
Change the name. deleteWindow -> autoCloseWindow

### ISSUE THREAD

**Issue by Atria64** [Atria64/TwD3#21]
# Summary
I would like to change the internal name of the function that closes the window automatically when the two windows are detected.
I'm afraid to "delete".

**Comment by loiscodes** [comment]
I'll take this one

**Comment by Atria64** [comment]
@loiscodes thank you!
If you can solve this issue, please pull develop branch and work!
I`ll assign you.

**Comment by SimoSultan** [comment]
I have changed them all and created a PR

**Comment by Atria64** [comment]
@SimoSultan Thank you for your PR!
I reviewed. Please a bit change.

**Comment by Atria64** [comment]
This issue solved by #22.
Thank you : )
